version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: echo "Running go tests!"
      - run:
          name: Run unit tests
          command: |
            go test

workflows:
  version: 2
  hello-Workflow:
    jobs:
      - build
