version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7

workflows:
  "Hello Workflow":
    jobs:
      - hello/hello-build

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: echo "Running go tests!"
      - run:
          name: Run unit tests
          command: |
            go test